#-------------------------------
# General Site Settings

title: GPCR Data Explorer
description: The GPCR Consortium is a not for profit entity formed to bring together industry and academic scientists to advance GPCR research for drug development.
email: cristina@isi.edu

# NOTE: The Logo and Background image are defined in the all.sass document.

#menu:
#- {name: Explorer, url: '/'}
#- {name: Help, url: '/using-the-data-explorer/'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'The GPCR Data Explorer contains data generated during the process of GPCR structure determination.'
  #rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  #rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-76441744-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  The GPCR Data Explorer contains data generated during the process of GPCR structure determination.
